### ISSUE TITLE
[Bug]: xquic regularly and consistently fails Interop Runner runs

### ISSUE THREAD

**Issue by marten-seemann** [alibaba/xquic#518]
### What happened?

The xquic image runs into timeouts and fails the interop runner runs. This happens every time (and triggers an email notification to me). Example run: https://github.com/quic-interop/quic-interop-runner/actions/runs/19495022675

Can you please investigate and fix this?

### Steps To Reproduce

Run the interop runner.

### Relevant log output

```shell

```

**Comment by marten-seemann** [comment]
I just merged the PR. Might be easier to debug if you run it locally though.

**Comment by Sy0307** [comment]
Thanks for merging the PR, but I still do not find the error log on https://interop.seemann.io/. But CI showed that the log files had been uploaded. Can you give some help?

**Comment by Sy0307** [comment]
Have fixed the issue on xquic with neqo in #520 , but xquic still have interoperability issue on kwik & quinn. We will keep researching on the root cause.
